# Define a goal (print all squares to the provided index)
# A request message is sent from an action client to an action server initiating a new goal.
int32 index
---
# Result
# A result message is sent from an action server to an action client when a goal is done.
# This will be the full list of squares
int32[] squares
---
# Feedback
# Feedback messages are periodically sent from an action server to an action client with updates about a goal.
# here we send a partial list of squares
int32[] partial_squares

